### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Nosnahc** [pmatuszy/signal-cli-on-Raspberry-PI---WORKS-#2]
Hello,
I followed all the instructions line by line using sudo if necessary but an error appears at one point telling me that it is impossible to find Cargo.

I did the manipulation twice out of two clean installs.

Can you correct the script or tell me where I am making a mistake please?

Edit : Raspberry Pi 4 1Gb
OS : Octoprint Version 1.9.0

**Comment by pmatuszy** [comment]
should be ok now.
